server:
  port: "8000"
  mode: "debug"

database:
  host: "localhost"
  port: "5432"
  user: "scott"
  password: ""
  dbname: "password_manager"
  sslmode: "disable"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

jwt:
  secret: "change-this-super-secret-key-in-production-use-env-var"
  expire_time: 24

email:
  host: "smtp.gmail.com"
  port: 587
  username: ""
  password: ""
  from: "SecureVault <noreply@securevault.com>"

hibp:
  api_key: ""